### ISSUE TITLE
مجراها ومرساها

### ISSUE THREAD

**Issue by munzirtaha** [khaledhosny/quran-data#1]
لاحظت أن كلمتي مجراها ومرساها قد كتبت الألف الخنجرية على نبرة بشكل مغاير 
للموجود في المصحف الأميري وكذلك مصحف المدينة النبوية، ومع أن كتابتك لها بهذه الطريقة فيها اتساق مع مثيلاتها في بقية أجزاء المصحف أينما وردت الهاء بعد ياء أو ما يماثلها إلا أن مخالفة كلا المصحفين لهذا الرسم في هذا الموضع له سببه وبغض النظر عن السبب سواء كان تقنيا أو لتوضيح النبرة أو قواعد الرسم فأرى ألا نخالف أبدا الرسم الذي أمامنا فغاية المشروع هو محاكاة الخط الأميري وليس استحداث خط أجمل منه

وفقكم الله

**Comment by khaledhosny** [comment]
<div dir="rtl">
هذه مشكلة في الخط و ليس النص، أصلحتها هناك.
</div>
