### ISSUE TITLE
عدة ملاحظات على وصل الكلمات وفصلها

### ISSUE THREAD

**Issue by hubaishan** [khaledhosny/quran-data#11]
كنت قد كتبت ملاحظات على نسخة المصحف التي نشرها مجمع الملك فهد بخط حفض ونشرت في ملتقى أهل التفسير والحمد لله لم يتعقبها أحد ورواد الملتقى من أهل الاختصاص في ذلك ثم رأيت في نسختكم نفس الملاحظات تقريبا فنرجو مراجعتها وتصويبها

http://vb.tafsir.net/tafsir46414/#.WH7xoGpBpPY

**Comment by khaledhosny** [comment]
بالنسبة لوصل ما حقه الفصل، راجعت المواضع الثلاثة على المصحف الأميري (الطبعة الرابعة) و مصحف مجمع المدينة، و قد وافقا المعتمد هنا ما عدا الآية ٥١ من فصلت فهي مفصولة في المصحف الأميري و موصولة في الآخر، و قد فصلتها اتباعًا للمصحف الأميري.

أما فصل ما حقه الوصل، فواو العطف موصولة دوما في المصحف الأميري، لذا وصلت هذين (رغم أن واو العطف قبل اللام ألف تبدو في أحيان كثيرة مفصولة في المصحف الأميري، لكن الأرجح أن هذا من عيوب الطبع بالحروف الرصاص).

أما همزة الاستفهام المتبوعة بواو الاستئناف، فتبدو لي مفصولة عن الكلمة التي تليها في كل المواضع التي نظرت إليها في المصحف الأميري، فلا أدري ما الصواب هنا. ربما الأفضل فصلها بمسافة رفيعة لا تنفصل، هكذا يظهر فراغ صغير بينها و بين الكلمة التي تليها دون أن ينكسر السطر بينهما؟

**Comment by hubaishan** [comment]
المسافات في خط الخطاطين لا يعتمد عليها في إثبات فصل الكلمات التي لا توصل حروفها
هذا توضيح من سورة يوسف/11 في (ما لك)
وسورة الحجر :32 حيث أنك فصلت بين ما الاستفهامية والجار والمجرور (لك)
الصور من مصحف المدينة النبوية المنشور في موقع مجمع الملك فهد
نلاحظ في الصورة الأولى من سورة الحجر:32 كلمتي (ما لك) يقعان في نفس الموقع الإعرابي لكلمتي (ما لك) في سورة يوسف وأنت فصلت في آية الحجر ووصلت في آية يوسف ما ذكرته من أنها موصولة في مصحف المدينة فهذا غير صحيح لأنك اعتمدت على مجرد النظر والخطاط يضيق بين المسافات بين الكلمات جدًّا نلاحظ في سورة يوسف: 11 المسافة بين (نا) من كلمة (أبانا) مساوية للمسافة بين (ما) و(لك) فلماذا اعتبرت أن هذه مفصولة وهذه موصولة كذلك (لا) بينها وبين (تأمنا) 4 بكسل فلماذا لا تعتبرها موصولة وكذلك بين (تأمنا) و(على)

لماذا لم تأخذ بتصرف المجمع في برنامج مصحف النشر الحاسوبي بإصداريه الأول والثاني حيث فصلوا هذه الكلمات.

فالعبرة في الفصل والوصل بما يقرره أئمة اللغة، وما خالف قواعد اللغة من رسم المصحف فإن علماء الرسم والضبط يذكرونه وينصصون عليه

**Comment by hubaishan** [comment]
![ff](https://cloud.githubusercontent.com/assets/2285457/22182702/0bf32ae6-e0bd-11e6-83c6-3c22563286ab.png)

**Comment by hubaishan** [comment]
![tt](https://cloud.githubusercontent.com/assets/2285457/22182714/4e2ae84a-e0bd-11e6-8bfc-9b26cd54bf7e.png)

**Comment by hubaishan** [comment]
صدرت حديثًا عن مجمع الملك فهد لطباعة المصحف النسخة 0.13 من خط حفص والنص القرآني بخط حفص
https://fonts.qurancomplex.gov.sa/wp02/حفص
وقد تم إصلاح جميع الملاحظات التي استدركتها على النسخة السابقة
