### ISSUE TITLE
بعض علامات الوقف مخالفة للمصحف الأميري

### ISSUE THREAD

**Issue by noureddin** [khaledhosny/quran-data#18]
<div dir="rtl">

السلام عليكم ورحمة الله وبركاته.

جزاك الله خير الجزاء على هذا العمل وجعله خالصا لوجهه الكريم.

لاحظت أن بعض علامات الوقف في هذا النص مخالفة للمصحف الأميري. إليك بيانها:

السورة | رقم الآية | النص | التصحيح
--:|--:|--:|--:
آل عمران | ٧ | هُوَ ٱلَّذِیۤ أَنزَلَ عَلَیۡكَ ٱلۡكِتَـٰبَ مِنۡهُ ءَایَـٰتࣱ مُّحۡكَمَـٰتٌ هُنَّ أُمُّ ٱلۡكِتَـٰبِ وَأُخَرُ مُتَشَـٰبِهَـٰتࣱۖ فَأَمَّا ٱلَّذِینَ فِی قُلُوبِهِمۡ زَیۡغࣱ فَیَتَّبِعُونَ مَا تَشَـٰبَهَ مِنۡهُ ٱبۡتِغَاۤءَ ٱلۡفِتۡنَةِ وَٱبۡتِغَاۤءَ تَأۡوِیلِهِۦۖ وَمَا یَعۡلَمُ تَأۡوِیلَهُۥۤ إِلَّا ٱللَّهُۗ وَٱلرَّ ٰسِخُونَ فِی ٱلۡعِلۡمِ یَقُولُونَ ءَامَنَّا بِهِۦ كُلࣱّ مِّنۡ عِندِ رَبِّنَاۗ وَمَا یَذَّكَّرُ إِلَّاۤ أُو۟لُوا۟ ٱلۡأَلۡبَـٰبِ | صلى، صلى، قلى، قلى في هذا النص،<br>[جائز، صلى، لازم، جائز في الأميري](https://archive.org/stream/MmSL7H/MmSL7HB#page/n62/mode/1up)
الإسراء | ٨ | وَإِنۡ عُدتُّمۡ عُدۡنَاۚ وَجَعَلۡنَا جَهَنَّمَ لِلۡكَـٰفِرِینَ حَصِیرًا | جائز في هذا النص،<br>[لازم في الأميري](https://archive.org/stream/MmSL7H/MmSL7HB#page/n364/mode/1up)
العنكبوت | ٦٤ | وَإِنَّ ٱلدَّارَ ٱلۡءَاخِرَةَ لَهِیَ ٱلۡحَیَوَانُۚ لَوۡ كَانُوا۟ یَعۡلَمُونَ | جائز في هذا النص،<br>[لازم في الأميري](https://archive.org/stream/MmSL7H/MmSL7HB#page/n528/mode/1up)

**Comment by khaledhosny** [comment]
<div dir="rtl">

شكرا لك أخی الكریم. علامات الوقف فی هذا البنص لا توافق دائما المصحف الأمیری، وقد كنت بدأت من مدة مراجعتها على المصحف الأمیری لكن انشغلت عنها.
