### ISSUE TITLE
علامة جواز الوقف وضعت خطأ مكان علامة الوصل أولى

### ISSUE THREAD

**Issue by munzirtaha** [khaledhosny/quran-data#2]
سورة البقرة الآية 102 (... لو كانوا يعلمون) قبلها علامة الوصل أولى لكن في هذا المصحف وضعت علامة جواز الوقف وهذا خلاف المصحف الأميري ومصحف المدينة النبوية

![2-102](https://cloud.githubusercontent.com/assets/2936425/16535435/e3236202-3fef-11e6-8daa-bb08f1eef84e.jpeg)

**Comment by munzirtaha** [comment]
وكذلك الآية التي بعدها الوقف في كلمة خير نفس الخطأ

**Comment by khaledhosny** [comment]
<div dir="rtl">
في الطبعة الرابعة في كلا الموضعين جواز الوقف. ذكر في الطبعة الثانية تنقيح و تهذيب الوقوف في ثمانمئة موضع و أظن هذه منها.
</div>

**Comment by khaledhosny** [comment]
<div dir="rtl">
رابط لإعادة طبع للطبعة الثانية:
</div>

https://archive.org/stream/MmSL7H/MmSL7HB#page/n19/mode/1up

**Comment by munzirtaha** [comment]
هذا الموضوع يحتاج لعالم متخصص حتى يفتي فيه فأخشى ما أخشاه أن الطبعة الرابعة التي بين يديك ليست موثوقة كالطبعة الثانية فالأخيرة هي المشتهرة بأنها أصح الطبعات، وموافقة مصحف المدينة النبوية لها وهو المصحف السائر بين الناس في كل دول العالم نور على نور فلو اعتمدت هذه الوقفات التي بين يديك ستكون في أفضل أحوالها مرجوحة وسيسبب ذلك خلطا ونفورا عنه ولا أرى سببا يدفعك لذلك فتميز المصحف الأميري على مصحف المدينة أساسا هو بخطه المناسب للبرمجة الحاسوبية أما أن نخالف المصحف الذي بين أيدي الناس فلا أراه

**Comment by khaledhosny** [comment]
<div dir="rtl">
على حد علمي لا اختلاف في الطبعتين الثالثة و الرابعة عن الثانية، و أظنك تنظر إلى الطبعة الأولى.
</div>

**Comment by munzirtaha** [comment]
صدقت، فعلا كنت أنظر للطبعة الأولى وأحسبها الثانية. أما الآن وقد اختلف المصحفان فهذا الموضوع أكبر مني فافعل ما تشاء
