### ISSUE TITLE
Hamza in ( أُو۟لَـٰۤئِكَ ) at the top and not ( أُو۟لَـٰۤىِٕكَ )

### ISSUE THREAD

**Issue by rrefky** [khaledhosny/quran-data#23]
I hope this isn't an issue but here is a note:
(found in many instances)

Comparison In Mushaf:
![image](https://user-images.githubusercontent.com/11573349/163711660-6dc760b4-6aa9-45ee-b869-3cf1fcab6db7.png)

Displayed with Amiri Font:
![image](https://user-images.githubusercontent.com/11573349/163711787-a6925021-e760-44d1-afd8-e24b3995cc0f.png)

**Comment by khaledhosny** [comment]
You need to use Amiri Quran font.

**Comment by rrefky** [comment]
You are right! the problem is with the "Amiri-Bold.ttf" thank you.

**Comment by khaledhosny** [comment]
I don’t currently provide a bold version of Amiri Quran.

**Comment by rrefky** [comment]
Thank you, I am closing this issue as resolved.

Maybe would be helpful for others if you could add a small comment in the Wiki to only use the AmiriQuran.ttf file if that is the case.

Note: https://github.com/aliftype/amiri/blob/main/Amiri-Bold.ttf

Thanks for the quick reaction. السلام عليكم

**Comment by khaledhosny** [comment]
I think I’ll update the text to use hamza below regardless of the font.
