### ISSUE TITLE
re Sura 22

### ISSUE THREAD

**Issue by OmarKN** [khaledhosny/quran-data#25]
Salam. New for me to be here.
You may know this already:

v.11 akhira should have lam alif 
v.21 maqaami`u has normal alif in my mushaf.
Are there generally speaking great variations re. normal vs. dagger alif in the musahifs?
/OmarKN

**Comment by khaledhosny** [comment]
> v.11 akhira should have lam alif

This depends on the font, if you use Amiri Quran it will render correctly. I’ll try to use the Unicode-approved sequence for this. but it might still not render correctly in most fonts.

> v.21 maqaami`u has normal alif in my mushaf.

It has small alef in Azhar and Madina mushaf.

>  Are there generally speaking great variations re. normal vs. dagger alif in the musahifs?

I’m not an expert in this, but variations do exist. This text follows Hafs reading masahif of Azhar and Madina.

**Comment by OmarKN** [comment]
Salam Khaled,

The font I now - was advised to - use for macOS is Kitab, and I think you were involved in its creation, right?

This font is very beautiful.


However, AFAIunderstand, Kitab cannot be used as webfont. (?!)

There is the Google font Noto Naskh Arabic, but it’s not as good as Kitab (or Amiri Quran) see link below.


So for now, I use the Quranic Arabic from sites such as islamawakened.com

Then I correct the pasted result, such as missing ALIF or fatha where there should be at least a small ALIF, and then I use it for our webpage.

The css fonts our webpage are 
font-family: OpenSans, Geneva, Lopash, Lucida Grande, Tahoma, Verdana, "Helvetica Neue", Helvetica, "Hiragino Sans GB", Arial, sans-serif;

One of them, I don’t know which, is responsible for some decent Arabic font presentation.

Please compare the two fonts here https://www.livingislam.org/d/jih_e.html <https://www.livingislam.org/d/jih_e.html>#theno 

1st. The defined font by one of the above-mentioned
2nd. The Google 'Noto Naskh Arabic', serif; font


As it is, I'm still learning how to improve things.

/
with best regards & salam, Omar KN, Stockholm, Sweden
The blessings and peace of Allah on the Prophet, his Family, and his Companions.

**Comment by khaledhosny** [comment]
> The font I now - was advised to - use for macOS is Kitab, and I think you were involved in its creation, right?

This text used a different and incompatible way of encoding medial seat-less hamza, I learnt later a more Unicode-sanctioned way but didn’t update the text. I just updated it, so it should show correctly in Kitab as well.
