### ISSUE TITLE
كلمة تبع ينقصها شرطتان

### ISSUE THREAD

**Issue by munzirtaha** [khaledhosny/quran-data#4]
في سورة البقرة الآية 38 كلمة تبع تداخلت كسرة الباء مع حرف العين وهي تحتاج شرطتين فتكون هكذا
![screenshot_20160703_201157](https://cloud.githubusercontent.com/assets/2936425/16546675/c51e3c2a-415a-11e6-96e1-b2599e2e4fc3.png)
حيث الحركة مرسومة بصورة جميلة ومطابقة لكل من المصحف الأميري ومصحف المدينة النبوية

**Comment by munzirtaha** [comment]
يبدو لي الآن أن هذه العلة لا يجب أن تعالج هنا بإضافة التطويل يدويا وإنما يجب أن تعالج في الخط الأميري قرآن حتى تنطبق على جميع المواضع

**Comment by khaledhosny** [comment]
<div dir="rtl">
بالطبع، مثل هذا النوع من المشاكل يُحل في الخط. عموما أتفادى وضع التطويل يدويا إلا عند الضرورة الملحة.
</div>
